version: '3'
services:

  nginx:
    image: nginx:alpine
    container_name: "nginx"
    volumes:
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./docker/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
      - "./src:/var/www/ragnarok"
      - "./logs/nginx/:/var/log/nginx"
    ports:
      - "8000:80"
      - "3000:443"
    environment:
      - NGINX_HOST=${NGINX_HOST}
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
    depends_on:
      - php-fpm
      - mysqldb

  php-fpm:
    build: "./docker/php"
    container_name: 'php-fpm'
    volumes:
      - "./src:/var/www/ragnarok"
    env_file:
        - ".env"
    depends_on:
      - mysqldb

  redis:
    image: redis:latest
    container_name: "redis"
    depends_on:
      - php-fpm
    expose:
      - "6379"

  mysqldb:
    image: mysql:${MYSQL_VERSION}
    container_name: ${MYSQL_HOST}
    restart: always
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - "./docker/mysql/data:/var/lib/mysql"
      - "./logs/mysql/:/var/log/mysql"
      - "./docker/mysql/conf.d:/etc/mysql/conf.d"
    ports:
      - "8989:3306"